[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
# A basic redirect rule
[[redirects]]
  from = "/middag"
  to = "https://www.notion.so/Hold-din-egen-Gr-nne-Middag-5ac2d24fb8564df3907afc6f00c43270"

# A basic redirect rule
[[redirects]]
  from = "/valgdebatkort"
  to = "https://actionnetwork.org/event_campaigns/valgmodekortet-gor-valget-gront-ved-at-kortlaegge-og-deltage-i-valgmoder"

  # A basic redirect rule
[[redirects]]
  from = "/finansministeriet"
  to = "https://actionnetwork.org/forms/hjaelp-mig-gore-finansministeriet-gront-nu/"

  # A basic redirect rule
[[redirects]]
  from = "/indsamling"
  to = "https://www.actionnetwork.org/fundraising/vaer-med-til-at-forpligte-politikerne-pa-at-handle-for-klima-natur-og-miljo/"

  # A basic redirect rule
[[redirects]]
  from = "/valgdebatguide"
  to = "https://www.notion.so/G-r-valgm-derne-gr-nne-94cdb4e31ca64d278b986e1c0f340c96/"

  # A basic redirect rule
[[redirects]]
  from = "/"
  to = "https://deltagerdanmarkpoke.azurewebsites.net/"


