[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
# A basic redirect rule
[[redirects]]
  from = "/middag"
  to = "https://www.notion.so/Hold-din-egen-Gr-nne-Middag-5ac2d24fb8564df3907afc6f00c43270"

# A basic redirect rule
[[redirects]]
  from = "/valg-debat-kort"
  to = "https://actionnetwork.org/event_campaigns/valgmodekortet-gor-valget-gront-ved-at-kortlaegge-og-deltage-i-valgmoder"
